import pytest

from solar_plus_intelbras.solar_plus_intelbras import SolarPlusIntelbras


@pytest.fixture
def solar_plus_intelbras() -> SolarPlusIntelbras:
    return SolarPlusIntelbras("test@email.com", "test")


@pytest.fixture
def login_response() -> dict:
    return {
        "user": {
            "id": 6851,
            "email": "test@email.com",
            "name": "Test",
            "cpf": "",
            "picture": "",
            "preferences": {
                "currency": "BRL",
                "timezone": "-3",
                "temperatureUnit": "c",
                "sendWeatherNotification": True,
                "sendEnergyTodayNotification": True,
                "sendAlertNotification": True,
            },
        },
        "accessToken": {
            "exp": 1737175716,
            "expAt": "2025-01-18 01:48:36",
            "iat": 1737175416,
            "accessJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InBpY3R1cmUiOiIiLCJpZCI6Njg1MSwiZW1haWwiOiJjb250YXRvLmh1ZHNvbmJyZW5kb25AZ21haWwuY29tIiwibmFtZSI6Ikh1ZHNvbiBCcmVuZG9uIiwiY3BmIjoiIiwicGhvbmUiOiIiLCJjcmVhdGVkQXQiOiIyMDI0LTEyLTE2VDE0OjQ5OjU2LjYxMDY5OC0wMzowMCIsImFjdGl2YXRlZEF0Ijp7IlRpbWUiOiIyMDI0LTEyLTE2VDE0OjQ5OjU2LjYwODEwNS0wMzowMCIsIlZhbGlkIjp0cnVlfSwibGFzdExvZ2luIjoiMjAyNS0wMS0xNyAyMzoyNToxNC4zOTAwMjg0MzYgLTAzMDAgLTAzIG09KzUyMzkyLjQ4ODc5MjE1MSIsInByZWZlcmVuY2VzIjp7ImN1cnJlbmN5IjoiQlJMIiwidGltZXpvbmUiOiItMyIsInRlbXBlcmF0dXJlVW5pdCI6ImMiLCJzZW5kV2VhdGhlck5vdGlmaWNhdGlvbiI6dHJ1ZSwic2VuZEVuZXJneVRvZGF5Tm90aWZpY2F0aW9uIjp0cnVlLCJzZW5kQWxlcnROb3RpZmljYXRpb24iOnRydWV9LCJyZWdpc3RyYXRpb25Ub2tlbiI6ImQxbWNVRzNVSjA5UHN3d0JDLXVFUDk6QVBBOTFiRzJ4Z3dXUDIzVFhab0tiejVIamZpQW9EbnIxeGEtT1haVTZDMXVEQWIyczZPU3NkRHdMQ3VYTWxkdnBYM0ZJcF9jQloxRU4zU2xsZm5nWmVCYU1aNUNsLWhvcGNLajNhWnRWTTE0MEsyT1U4Tno3eHMiLCJhY3RpdmF0aW9uQ29kZSI6ImU2YjE2OGRkZjc0M2QwOWE4OGU2NmYwZWZhMDZiMDE1In0sImV4cCI6MTczNzE3NTcxNiwiaWF0IjoxNzM3MTc1NDE2LCJjb2RlIjoiIiwicm9sZSI6ImNsaWVudCJ9.FXOp76WgRRemmiOr2z4ML6QVEG1fbDYk1LfYK_hm3vs",
        },
        "refreshToken": {
            "exp": 1737261816,
            "expAt": "2025-01-19 01:43:36",
            "iat": 1737175416,
            "refreshJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InBpY3R1cmUiOiIiLCJpZCI6Njg1MSwiZW1haWwiOiJjb250YXRvLmh1ZHNvbmJyZW5kb25AZ21haWwuY29tIiwibmFtZSI6Ikh1ZHNvbiBCcmVuZG9uIiwiY3BmIjoiIiwicGhvbmUiOiIiLCJjcmVhdGVkQXQiOiIyMDI0LTEyLTE2VDE0OjQ5OjU2LjYxMDY5OC0wMzowMCIsImFjdGl2YXRlZEF0Ijp7IlRpbWUiOiIyMDI0LTEyLTE2VDE0OjQ5OjU2LjYwODEwNS0wMzowMCIsIlZhbGlkIjp0cnVlfSwibGFzdExvZ2luIjoiMjAyNS0wMS0xNyAyMzoyNToxNC4zOTAwMjg0MzYgLTAzMDAgLTAzIG09KzUyMzkyLjQ4ODc5MjE1MSIsInByZWZlcmVuY2VzIjp7ImN1cnJlbmN5IjoiQlJMIiwidGltZXpvbmUiOiItMyIsInRlbXBlcmF0dXJlVW5pdCI6ImMiLCJzZW5kV2VhdGhlck5vdGlmaWNhdGlvbiI6dHJ1ZSwic2VuZEVuZXJneVRvZGF5Tm90aWZpY2F0aW9uIjp0cnVlLCJzZW5kQWxlcnROb3RpZmljYXRpb24iOnRydWV9LCJyZWdpc3RyYXRpb25Ub2tlbiI6ImQxbWNVRzNVSjA5UHN3d0JDLXVFUDk6QVBBOTFiRzJ4Z3dXUDIzVFhab0tiejVIamZpQW9EbnIxeGEtT1haVTZDMXVEQWIyczZPU3NkRHdMQ3VYTWxkdnBYM0ZJcF9jQloxRU4zU2xsZm5nWmVCYU1aNUNsLWhvcGNLajNhWnRWTTE0MEsyT1U4Tno3eHMiLCJhY3RpdmF0aW9uQ29kZSI6ImU2YjE2OGRkZjc0M2QwOWE4OGU2NmYwZWZhMDZiMDE1In0sImV4cCI6MTczNzI2MTgxNiwiaWF0IjoxNzM3MTc1NDE2LCJjb2RlIjoiIiwicm9sZSI6ImNsaWVudCJ9.Y6JFTXgrcc-SD1nYutJj8kwUVvFgS8YaGDLMavNA7V4",
        },
        "accessTokenContaUnica": "",
        "refreshTokenContaUnica": "",
        "loginType": "code",
        "requestIP": "187.19.163.111",
        "registrationToken": "",
        "code": "",
        "role": "client",
        "businessAccount": {
            "id": 0,
            "createdAt": "0001-01-01T00:00:00Z",
            "updatedAt": "0001-01-01T00:00:00Z",
            "userOwnerID": 0,
            "userOwner": {
                "id": 0,
                "createdAt": "0001-01-01T00:00:00Z",
                "updatedAt": "0001-01-01T00:00:00Z",
                "lastLogin": "",
                "email": "",
                "clientID": "",
                "clientSecret": "",
                "picture": "",
                "registrationToken": "",
                "passwordRecoveryCode": "",
                "passwordRecoveryExpiresAt": {
                    "Time": "0001-01-01T00:00:00Z",
                    "Valid": False,
                },
                "name": "",
                "cpf": "",
                "phone": "",
                "activationCode": "",
                "activatedAt": {"Time": "0001-01-01T00:00:00Z", "Valid": False},
                "sessions": None,
                "pushesNotification": None,
                "preferences": {
                    "sendWeatherNotification": None,
                    "sendEnergyTodayNotification": None,
                    "sendAlertNotification": None,
                },
            },
            "name": "",
            "code": "",
            "cnpj": "",
            "webSite": "",
            "phone": "",
        },
    }


@pytest.fixture
def plants() -> dict:
    return {
        "limit": 10,
        "page": 1,
        "sort": "",
        "total_rows": 1,
        "total_rows_in_this_page": 1,
        "total_pages": 1,
        "rows": [
            {
                "id": 2171,
                "picture": "",
                "name": "User Test",
                "userOwnerID": 1111,
                "userOwner": {
                    "id": 1151,
                    "createdAt": "2024-12-16T14:49:56.610698-03:00",
                    "updatedAt": "2025-01-23T00:58:20.285852-03:00",
                    "lastLogin": "2025-01-23 00:58:20.285268014 -0300 -03 m=+36384.151669507",
                    "email": "test@email.com",
                    "clientID": "",
                    "clientSecret": "",
                    "picture": "",
                    "registrationToken": "d1ssUG3UKK9PswwBC-uEP9:APA91bG2xgwWP23TXZoKbz5HjfiAoDnr1xa-OXZU6C1uDAb2s6OSsdDwLCuXMldvpX3FIp_cBZ1EN3SllfngZeBaMZ5Cl-hopcKj3aZtVM140K2OU8Nz7xs",
                    "passwordRecoveryCode": "",
                    "passwordRecoveryExpiresAt": {
                        "Time": "0001-01-01T00:00:00Z",
                        "Valid": False,
                    },
                    "name": "User Test",
                    "cpf": "",
                    "phone": "",
                    "activationCode": "sdf168ssf743d09a88e66f0efa06b015",
                    "activatedAt": {
                        "Time": "2024-12-16T14:49:56.608105-03:00",
                        "Valid": True,
                    },
                    "sessions": None,
                    "pushesNotification": None,
                    "preferences": {
                        "currency": "BRL",
                        "timezone": "-3",
                        "temperatureUnit": "c",
                        "sendWeatherNotification": True,
                        "sendEnergyTodayNotification": True,
                        "sendAlertNotification": True,
                    },
                },
                "users": [],
                "business_accounts": None,
                "weather": {
                    "current": {
                        "cloud": 75,
                        "is_day": 1,
                        "temp_c": 31.2,
                        "temp_f": 88.2,
                        "humidity": 66,
                        "wind_dir": "ESE",
                        "wind_kph": 18,
                        "condition": {
                            "code": 1003,
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "text": "Parcialmente nublado",
                        },
                        "wind_degree": 109,
                        "last_updated": "2025-01-22 15:00",
                        "last_updated_epoch": 1737568800,
                    },
                    "location": {
                        "lat": 0,
                        "long": 0,
                        "name": "Test",
                        "tz_id": "America/Fortaleza",
                        "region": "Test",
                        "country": "Brazil",
                        "localtime": "2025-01-22 15:09",
                        "localtime_epoch": 1737569379,
                    },
                },
                "street": "Test",
                "number": "",
                "district": "Test",
                "city": "Test",
                "state": "RN",
                "country": "BR",
                "zip": "59999-999",
                "latitude": -5.933342,
                "longitude": -35.33916,
                "online": False,
                "offgrid": False,
                "status": "WAITING",
                "price": 0.92,
                "capacityInstalled": 5,
                "modulesAmount": 10,
                "last_record": "2025-01-22T18:28:16.986982-03:00",
                "installed_at": "0000-12-31T20:53:32-03:06",
                "createdAt": "2024-12-16T14:49:57.108865-03:00",
                "updatedAt": "2025-01-23T00:52:45.08055-03:00",
                "metrics": {
                    "energyToday": 21.7,
                    "energyTotal": 139.5,
                    "currentPower": 0,
                    "totalEconomy": 128.34000232815742,
                    "todayEconomy": 19.964000362157822,
                    "economyOfLast30": 127.69600231647493,
                    "yearEconomy": 0,
                    "energyOfLast30": 138.8,
                    "savedCo2": 47.513702392578125,
                    "savedTrees": 0.047513701021671295,
                    "savedCoal": 0.055799998342990875,
                },
                "components": {
                    "inverters": 1,
                    "dataloggers": 1,
                    "modules": 0,
                    "alerts": 5,
                    "todayAlerts": 0,
                    "chargeControllers": 0,
                },
            }
        ],
    }
